[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg", "tokio_unstable",
  "--cfg", "getrandom_backend=\"wasm_js\"",
  "-C", "debuginfo=0",
  "-C", "strip=symbols",
]
runner = "wasm-bindgen-test-runner"
